[zh-CN]
  title = "保持好奇心"
  languageName = "中文"
  weight = 1
  contentdir = "content/zh-CN"

[en]
  title = "Stay hungry. Stay foolish."
  languageName = "English"
  weight = 2
  contentdir = "content/en"
